/**
 * Client-side PDF receipt rendering for a single remittance payout, built
 * with `jspdf` so it stays lightweight and dependency-free of any
 * server-side rendering path (jsPDF draws directly to a canvas-backed
 * document, so this only ever runs in the browser).
 */
import type { ReceiptData } from "@/components/remittance/ReceiptModal";

const PAGE_MARGIN = 48;
const LINE_HEIGHT = 20;

/** Builds the receipt document and returns it, ready to save or print. */
export async function buildRemittanceReceiptPdf(data: ReceiptData) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "a4" });

  let y = PAGE_MARGIN;
  const left = PAGE_MARGIN;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(20);
  doc.text("Transaction Receipt", left, y);
  y += LINE_HEIGHT * 2;

  const field = (label: string, value: string) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(120);
    doc.text(label, left, y);
    y += 14;
    doc.setFontSize(12);
    doc.setTextColor(20);
    doc.text(value, left, y);
    y += LINE_HEIGHT;
  };

  const divider = () => {
    doc.setDrawColor(230);
    doc.line(left, y, 595 - PAGE_MARGIN, y);
    y += LINE_HEIGHT;
  };

  field("Date & Time", new Date(data.timestamp).toLocaleString());
  divider();

  field("Transaction Hash", data.transactionHash);
  field("Anchor Reference", data.anchorReference);
  if (data.anchorName) field("Anchor", data.anchorName);
  divider();

  field("Amount Sent", data.amountSent);
  field("Amount Received", data.amountReceived);
  field("Exchange Rate", data.exchangeRate);
  field("Fees", data.fees);
  divider();

  if (data.senderName && data.recipientName) {
    field("Sender", data.senderName);
    field("Recipient", data.recipientName);
    divider();
  }

  doc.setFontSize(9);
  doc.setTextColor(160);
  doc.text(
    "Generated by StellarFlow Network - Verify transaction hash on stellar.expert",
    left,
    800,
  );

  return doc;
}

export async function downloadRemittanceReceiptPdf(
  data: ReceiptData,
): Promise<void> {
  const doc = await buildRemittanceReceiptPdf(data);
  doc.save(`receipt-${data.transactionHash.substring(0, 8)}.pdf`);
}
