'use client';

import React from 'react';
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
  PDFDownloadLink,
} from '@react-pdf/renderer';

// Define styles for the PDF
const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
  },
  title: {
    fontSize: 24,
    marginBottom: 20,
    textAlign: 'center',
    fontWeight: 'bold',
  },
  section: {
    marginBottom: 15,
  },
  label: {
    fontSize: 12,
    color: '#666',
    marginBottom: 4,
  },
  value: {
    fontSize: 14,
    marginBottom: 8,
  },
  divider: {
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    marginVertical: 15,
  },
  footer: {
    position: 'absolute',
    bottom: 40,
    left: 40,
    right: 40,
    fontSize: 10,
    textAlign: 'center',
    color: '#999',
  },
});

export interface ReceiptData {
  transactionHash: string;
  anchorReference: string;
  amountSent: string;
  amountReceived: string;
  exchangeRate: string;
  fees: string;
  timestamp: string;
  senderName?: string;
  recipientName?: string;
}

// PDF Document Component
const ReceiptDocument = ({ data }: { data: ReceiptData }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.title}>Transaction Receipt</Text>

      <View style={styles.section}>
        <Text style={styles.label}>Date & Time</Text>
        <Text style={styles.value}>{new Date(data.timestamp).toLocaleString()}</Text>
      </View>

      <View style={styles.divider} />

      <View style={styles.section}>
        <Text style={styles.label}>Transaction Hash</Text>
        <Text style={styles.value}>{data.transactionHash}</Text>
        
        <Text style={styles.label}>Anchor Reference</Text>
        <Text style={styles.value}>{data.anchorReference}</Text>
      </View>

      <View style={styles.divider} />

      <View style={styles.section}>
        <Text style={styles.label}>Amount Sent</Text>
        <Text style={styles.value}>{data.amountSent}</Text>

        <Text style={styles.label}>Amount Received</Text>
        <Text style={styles.value}>{data.amountReceived}</Text>

        <Text style={styles.label}>Exchange Rate</Text>
        <Text style={styles.value}>{data.exchangeRate}</Text>

        <Text style={styles.label}>Fees</Text>
        <Text style={styles.value}>{data.fees}</Text>
      </View>

      {data.senderName && data.recipientName && (
        <>
          <View style={styles.divider} />
          <View style={styles.section}>
            <Text style={styles.label}>Sender</Text>
            <Text style={styles.value}>{data.senderName}</Text>
            
            <Text style={styles.label}>Recipient</Text>
            <Text style={styles.value}>{data.recipientName}</Text>
          </View>
        </>
      )}

      <Text style={styles.footer}>
        Generated by StellarFlow Network • Verify transaction hash on stellar.expert
      </Text>
    </Page>
  </Document>
);

interface ReceiptModalProps {
  isOpen: boolean;
  onClose: () => void;
  receiptData: ReceiptData;
}

export function ReceiptModal({ isOpen, onClose, receiptData }: ReceiptModalProps) {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm">
      <div className="bg-white dark:bg-gray-800 rounded-lg shadow-xl w-full max-w-md p-6">
        <div className="flex justify-between items-center mb-6">
          <h2 className="text-xl font-semibold text-gray-900 dark:text-white">Transaction Complete</h2>
          <button 
            onClick={onClose}
            className="text-gray-500 hover:text-gray-700 dark:hover:text-gray-300"
          >
            &times;
          </button>
        </div>

        <div className="space-y-4 mb-8">
          <p className="text-sm text-gray-600 dark:text-gray-400">
            Your cross-border payment was successful. You can download the official receipt for your records.
          </p>
          <div className="bg-gray-50 dark:bg-gray-900 p-4 rounded-md">
            <div className="grid grid-cols-2 gap-2 text-sm">
              <span className="text-gray-500">Amount Sent:</span>
              <span className="font-medium text-gray-900 dark:text-white">{receiptData.amountSent}</span>
              <span className="text-gray-500">Amount Received:</span>
              <span className="font-medium text-gray-900 dark:text-white">{receiptData.amountReceived}</span>
              <span className="text-gray-500">Exchange Rate:</span>
              <span className="font-medium text-gray-900 dark:text-white">{receiptData.exchangeRate}</span>
            </div>
          </div>
        </div>

        <div className="flex justify-end gap-3">
          <button 
            onClick={onClose}
            className="px-4 py-2 text-sm font-medium text-gray-700 bg-gray-100 hover:bg-gray-200 rounded-md dark:bg-gray-700 dark:text-gray-300 dark:hover:bg-gray-600 transition-colors"
          >
            Close
          </button>
          
          {/* Client-side only PDF rendering to avoid hydration errors in Next.js */}
          {typeof window !== 'undefined' && (
            <PDFDownloadLink
              document={<ReceiptDocument data={receiptData} />}
              fileName={`receipt-${receiptData.transactionHash.substring(0, 8)}.pdf`}
              className="px-4 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 rounded-md transition-colors flex items-center gap-2"
            >
              {({ loading }) => (
                loading ? 'Generating PDF...' : 'Download Receipt'
              )}
            </PDFDownloadLink>
          )}
        </div>
      </div>
    </div>
  );
}
