import "@/config/env";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/ThemeProvider";
import { ProgressBarProvider } from "./components/TopLoadingBar";
import { UserProvider } from "./components/providers/UserProvider";
import { QueryProvider } from "./components/providers/QueryProvider";
import { ToastProvider } from "@/components/ui/ToastQueue";
import { FreighterWalletBoundary } from "./components/providers/FreighterWalletBoundary";
import Script from "next/script";
import SvgSprite from "@/components/icons/SvgSprite";

// subsets: ["latin"] restricts glyph maps to Latin characters only,
// avoiding loading Cyrillic/Greek/CJK blocks and reducing CSS payload.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "optional",
});

// Single variable font asset covers all app text weights; monospace utilities
// are mapped to this same face in globals.css to avoid a second font payload.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Prevent background flash before next-themes hydrates */}
        <style>{`html { background-color: #0d1117; }`}</style>
        {/* Preconnect to polyfill CDN (font files are self-hosted via next/font, so no Google Fonts preconnect needed) */}
        <link
          rel="preconnect"
          href="https://polyfill-library.fastly.dev"
        />
        {/* Preload the critical above-the-fold logo asset */}
        <link
          rel="preload"
          href="/sf.webp"
          as="image"
          type="image/webp"
          fetchPriority="high"
        />
        {/* Preload the SVG symbol sheet so icons render on first paint */}
        <link
          rel="preload"
          href="/sprite.svg"
          as="image"
          type="image/svg+xml"
          fetchPriority="low"
        />
        <Script
          id="polyfill-loader"
          strategy="afterInteractive"
          fetchPriority="low"
          dangerouslySetInnerHTML={{
            __html: `
              if (!('IntersectionObserver' in window) || 
                  !('ResizeObserver' in window) || 
                  !('fetch' in window) || 
                  !('Promise' in window)) {
                console.info('StellarFlow: Modern features missing. Loading on-demand polyfills...');
                var js = document.createElement('script');
                js.src = 'https://polyfill-library.fastly.dev/v3/polyfill.min.js?features=default,IntersectionObserver,ResizeObserver,fetch,Promise';
                document.head.appendChild(js);
              }
            `
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} antialiased`}
      >
        {/* Single global SVG symbol sheet — all icon <use> refs resolve here */}
        <SvgSprite />
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem={false}
          disableTransitionOnChange
        >
          <UserProvider>
            <QueryProvider>
              <ProgressBarProvider>
                <ToastProvider>
                  <FreighterWalletBoundary>
                    {children}
                  </FreighterWalletBoundary>
                </ToastProvider>
              </ProgressBarProvider>
            </QueryProvider>
          </UserProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
